default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: piazza
  password: <%= ENV["PIAZZA_DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: piazza_development

test:
  <<: *default
  database: piazza_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: piazza_production
  username: piazza
